version: "3.4"

services:
  app:
    build: .
    container_name: geeta-app
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    ports:
      - 5000:5000
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: geeta-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

# Important Commands
# docker run -d -p 27017:27017 --restart always -v mongodb_data:/data/db --name=geeta-db -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=pass mongo:latest
# docker stop $(docker ps | grep geeta- | awk '{print $1}')
